# Generated by Django 4.0.3 on 2022-04-30 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_review_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='parent',
        ),
    ]
