# Generated by Django 4.0.3 on 2022-03-26 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlesCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.ManyToManyField(to='articles.articles')),
            ],
        ),
        migrations.CreateModel(
            name='ArticlesCategoriesMini',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories_mini', models.ManyToManyField(to='articles.articlescategories')),
            ],
        ),
    ]
