# Generated by Django 4.0.3 on 2022-03-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_articlescategories_articlescategoriesmini'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlescategories',
            name='categories_title',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='articlescategoriesmini',
            name='categories_mini_title',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
